-- +goose Up
CREATE TABLE clients (
   -- id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    inn text NOT NULL,
    is_trash boolean NOT NULL DEFAULT 'f',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
-- integer 4 байта
-- bigint 8 байт
-- numeric размер переменной  для денег 
-- real  переменной 4 байта. точность в пределах 6 цифр. 
-- +goose Down
DROP TABLE clients;
